spring:
  application:
    name: spring-cloud-consumer
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    home-page-url-path: ${management.context-path}/beans
management:
  security:
    enabled: false
  port: 8089
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true
info:
   app:
      name: spring-cloud-producer
      version: 0.0.1
